Repository TeamChoiKang/antique-universe-back-end, pull requests merged in 2021-08, with the labels that each got.

#19 Feature/change way socket emit
  src/socket/character/index.js
Labels: ANTIQUE-UNIVERSE, with프론트, 기능추가

#20 [fix] Socket 연결 해제시 캐릭터 삭제되지 않던 버그 수정
  src/socket/index.js
Labels: ANTIQUE-UNIVERSE, 핫픽스

#21 Feat/signin signin
  package-lock.json
  package.json
  src/api/HttpClient.js
  src/api/auth/index.js
  src/api/index.js
  src/constants.js
  src/controllers/auth/index.js
  src/db/index.js
  src/index.js
  src/middleware/cors/index.js
  src/middleware/errorHandler/index.js
  src/middleware/json/index.js
  src/model/error/HttpError.js
  src/model/user/index.js
  src/package/cors/index.js
  src/package/db/index.js
  src/package/env/index.js
  src/package/http/index.js
  src/package/jwt/index.js
  src/package/pathAlias/index.js
  src/package/webServer/index.js
  src/queries/user/index.js
  src/routes/auth.js
  src/routes/index.js
  src/services/auth/KakaoOAuth.js
  src/services/auth/OAuth.js
  src/services/auth/constants.js
  src/services/auth/index.js
  src/services/user/index.js
Labels: ANTIQUE-UNIVERSE, 기능추가

#24 [feat] 하나의 소켓 이벤트는 하나의 동작만 하도록 분리
  src/socket/character/index.js
  src/socket/index.js
Labels: ANTIQUE-UNIVERSE, with프론트, 기능수정

#27 Feature/validate-token token
  src/controllers/auth/index.js
  src/routes/auth.js
  src/services/auth/index.js
Labels: ANTIQUE-UNIVERSE, 기능추가

#28 Feature/signin http method post
  .eslintrc.js
  src/api/auth/index.js
  src/controllers/auth/index.js
  src/routes/auth.js
Labels: ANTIQUE-UNIVERSE, with프론트, 기능수정

#26 Feature/append another village
  src/model/character/index.js
  src/model/scene/index.js
  src/model/scene/sceneKeys.js
  src/model/sceneGroup/index.js
  src/socket/character/index.js
  src/socket/index.js
  src/socket/scene/index.js
Labels: ANTIQUE-UNIVERSE, with프론트, 기능추가

#30 Feature/signup signup
  src/controllers/auth/index.js
  src/index.js
  src/model/error/HttpError.js
  src/queries/user/index.js
  src/routes/auth.js
  src/services/auth/index.js
  src/services/user/index.js
Labels: ANTIQUE-UNIVERSE, with프론트, 기능추가
