Repository TeamChoiKang/antique-universe-back-end, pull requests merged in 2021-07, with the labels that each got.

#7 [chore] 코드 포맷터 설정 및 issue/pr 템플릿 설정
  .eslintrc.js
  .github/ISSUE_TEMPLATE/-------------------.md
  .github/ISSUE_TEMPLATE/------------------.md
  .github/ISSUE_TEMPLATE/-----------------.md
  .github/PULL_REQUEST_TEMPLATE.md
  .pretterrc.js
  .vscode/extensions.json
  .vscode/settings.json
  package-lock.json
  package.json
  src/index.js
  src/socket/character/index.js
Labels: ANTIQUE-UNIVERSE, 환경설정

#10 [fix] 윈도우 맥 eol 호환을 위한 crlf, lf 통일
  .eslintrc.js
Labels: 버그수정, 핫픽스

#13 Refactoring/all
  src/model/character/index.js
  src/model/characterGroup/index.js
  src/socket/character/index.js
  src/socket/index.js
Labels: ANTIQUE-UNIVERSE, 리팩토링

#15 Feat/setting setting
  .eslintrc.js
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .pretterrc.js
  .prettierrc.js
  .vscode/settings.json
  jsconfig.json
  package-lock.json
  package.json
  src/index.js
  src/model/character/index.js
  src/model/characterGroup/index.js
  src/socket/character/index.js
  src/socket/index.js
Labels: ANTIQUE-UNIVERSE, 환경설정

#18 feat/setting hotfix
  .eslintrc.js
  .vscode/settings.json
Labels: ANTIQUE-UNIVERSE, 핫픽스, 환경설정
